version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vector_ai_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DB_PORT=5432
    ports:
      - 5432

  # Redis - result backend
  redis:
    image: redis:latest
    hostname: redis


  # RabbitMQ - queue
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"       
  
  # Django web server - celery master
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: sh ./run_web.sh
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    links:
      - rabbit
      - redis
  
  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit